

version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX

  build:
    commands:
      - echo Build started on `date`
      - echo Copying index.html to NGINX web root

  post_build:
    commands:
      - echo Restarting NGINX to apply changes

artifacts:
  files:
    - index.html
