

version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo Build started on `date`
      - echo Copying index.html to NGINX web root
      - sudo cp index.html /var/www/html/
      - sudo chmod 644 /var/www/html/index.html

  post_build:
    commands:
      - echo Restarting NGINX to apply changes
      - sudo systemctl restart nginx
      - echo Deployment finished on `date`

artifacts:
  files:
    - index.html
